include: package:lints/recommended.yaml

linter:
  rules:
    always_declare_return_types: true
    always_specify_types: true
    avoid_as: true
    avoid_catches_without_on_clauses: true
    avoid_empty_else: true
    avoid_print: true
    avoid_return_types_on_setters: true
    camel_case_types: true
    comment_references: true
    curly_braces_in_flow_control_structures: true
    empty_constructor_bodies: true
    file_names: true
    non_constant_identifier_names: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_is_empty: true
    prefer_single_quotes: true
    unnecessary_getters_setters: true
    unnecessary_string_escapes: true
    void_checks: true
