name: random_datetime
description: "Get randomized datetime objects. The plugin always you to add time-unit wise limitations to the randomized datetime objects. For example, Randomized DateTime where time is between 7 to 10 PM."
version: 0.0.1
homepage:
repository: https://github.com/ThisIsSidam/random_datetime

environment:
  sdk: ^3.5.4
dev_dependencies:
  lints: ^5.0.0
