name: random_datetime
description: "Get randomized DateTime objects. The plugin allows you to add time-unit wise limitations to the randomized DateTime. Ex: Randomized DateTime where time is between 7 to 10 PM."
version: 0.0.2
homepage:
repository: https://github.com/ThisIsSidam/random_datetime

environment:
  sdk: ^3.5.4
dev_dependencies:
  lints: ^5.0.0
dependencies:
  test: ^1.25.12
